image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r assets public/
    - cp index.html style.css script.js public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"
      when: always
