image: busybox

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public/
    - rm -rf public/public # Prevent infinite recursion
  artifacts:
    paths:
      - public
  only:
    - master
